name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ca-west-1
  ECR_REPOSITORY: project-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
          docker tag \
            $REGISTRY/$ECR_REPOSITORY:${{ github.sha }} \
            $REGISTRY/$ECR_REPOSITORY:latest

      - name: Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $REGISTRY/$ECR_REPOSITORY:latest
